version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
    steps:
      - checkout
      - run:
          working_directory: Delta
          command: dotnet build
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
    steps:
      - checkout
      - run:
          working_directory: Delta
          command: dotnet build
      - run:
          working_directory: Delta/Delta.AppServer.Test
          command: dotnet test --no-build --logger "trx"
      - run:
          working_directory: Delta/Delta.AppServer.Test
          command: |
            dotnet tool install -g trx2junit
            export PATH="$PATH:/root/.dotnet/tools"
            trx2junit TestResults/*.trx
          when: always
      - store_test_results:
          path: Delta/Delta.AppServer.Test/TestResults
      - store_artifacts:
          path: Delta/Delta.AppServer.Test/TestResults
          destination: TestResults
  docker:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          working_directory: Delta
          command: apk add --no-cache bash && ./build.sh
workflows:
  version: 2
  build:
    jobs:
      - build
      - test
      - docker
